In [1]:
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
tips=sns.load_dataset("tips")

In [4]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [6]:
median_tip=tips["tip"].median()
print(median_tip)

2.9

In [7]:
tips["tip_category"] = tips["tip"].apply(lambda x: "High" if x > median_tip else "Low")

In [8]:
tips.head()

   total_bill   tip     sex smoker  day    time  size tip_category
0       16.99  1.01  Female     No  Sun  Dinner     2          Low
1       10.34  1.66    Male     No  Sun  Dinner     3          Low
2       21.01  3.50    Male     No  Sun  Dinner     3         High
3       23.68  3.31    Male     No  Sun  Dinner     2         High
4       24.59  3.61  Female     No  Sun  Dinner     4         High

In [10]:
encoder=LabelEncoder()

In [11]:
tips["day"]=encoder.fit_transform(tips["day"])
tips["time"]=encoder.fit_transform(tips["time"])
tips["tip_category"]=encoder.fit_transform(tips["tip_category"])

In [16]:
X=tips[["total_bill", "day", "time", "size"]]
Y=tips["tip_category"]

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.20,random_state=42)

In [25]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [26]:
knn=KNeighborsClassifier(n_neighbors=5)

In [27]:
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [28]:
Y_pred=knn.predict(X_test)

In [29]:
accuracy=accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7346938775510204

In [30]:
cm=confusion_matrix(Y_test, Y_pred)
print(cm)

[[15  3]
 [10 21]]

In [31]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.60      0.83      0.70        18
           1       0.88      0.68      0.76        31

    accuracy                           0.73        49
   macro avg       0.74      0.76      0.73        49
weighted avg       0.77      0.73      0.74        49